#!/usr/bin/env bash

bytes() {
    local i

    for i in {0..255}; do
        printf "%02x\n" "$i"
    done; unset i
}

shuffle() {
    bytes | sort --random-sort
}

shuffle | sed -z "s/\n//g" | xxd -p -r >"${1:-./local/key.bin}"
