package main

import (
	"fmt"
	"io"
	"log"
	"os"
	"path/filepath"
	"slices"

	"github.com/mjwhitta/cplib"
)

func generateAdaptiveDLLTemplate() {
	var (
		err       error
		exports   []string
		f         *os.File
		funcIndex int
	)

	exports, err = getDllExports(flags.adaptHijackDll)

	if err != nil {
		log.Fatal("[!] Failed to get DLL exports: " + err.Error())
	}

	if flags.adaptHijackFunction != "" {
		funcIndex = slices.Index(exports, flags.adaptHijackFunction)
		if funcIndex == -1 {
			log.Fatalf(
				"[!] Function %s not found in DLL exports",
				flags.adaptHijackFunction,
			)
		}
		exports = slices.Delete(exports, funcIndex, funcIndex+1)
	} else {
		flags.adaptHijackFunction = "init"
	}

	if flags.runDll32Func != "" {
		funcIndex = slices.Index(exports, flags.runDll32Func)
		if funcIndex != -1 {
			exports = slices.Delete(exports, funcIndex, funcIndex+1)
		}
	}

	if flags.regSvr32 {
		funcIndex = slices.Index(exports, "DllRegisterServer")
		if funcIndex != -1 {
			exports = slices.Delete(exports, funcIndex, funcIndex+1)
		}
		funcIndex = slices.Index(exports, "DllUnregisterServer")
		if funcIndex != -1 {
			exports = slices.Delete(exports, funcIndex, funcIndex+1)
		}
	}

	// Source: https://github.com/mjwhitta/cplib/blob/main/cplib.go
	err = cplib.GenerateGo(
		flags.adaptHijackDll,
		filepath.Join("dll", "main_dll_generated.go"),
		"windows",
		exports,
		nil,
		false,
	)
	if err != nil {
		log.Fatal("[!] Failed to generate Go code for DLL: " + err.Error())
	}

	f, err = os.Create(filepath.Join("dll", "main_dll_entries_generated.go"))
	if err != nil {
		log.Fatal("[!] Failed to create Go file for DLL entries: " + err.Error())
	}
	defer f.Close()

	fmt.Fprint(f, "//go:build windows\n\n")
	fmt.Fprint(f, "// Code generated by Johnny Dllaze; DO NOT EDIT.\n")
	fmt.Fprint(f, "package main\n\n")

	fmt.Fprintf(f, "import \"C\"\n\n")

	err = writeExportToSB(f, flags.adaptHijackFunction)
	if err != nil {
		log.Fatal("[!] Failed to generate Go code for DLL: " + err.Error())
	}

	if flags.regSvr32 {
		err = writeExportToSB(f, "DllRegisterServer")
		if err != nil {
			log.Fatal("[!] Failed to generate Go code for DLL: " + err.Error())
		}
		err = writeExportToSB(f, "DllUnregisterServer")
		if err != nil {
			log.Fatal("[!] Failed to generate Go code for DLL: " + err.Error())
		}
	}

	if flags.runDll32Func != "" {
		err = writeExportToSB(f, flags.runDll32Func)
		if err != nil {
			log.Fatal("[!] Failed to generate Go code for DLL: " + err.Error())
		}
	}

}

func getDllExports(dllPath string) ([]string, error) {
	var (
		err     error
		exports []string
	)

	exports, err = cplib.PEExports(dllPath)
	if err != nil {
		return nil, fmt.Errorf("failed to parse DLL exports: %w", err)
	}

	return exports, nil
}

func writeExportToSB(iw io.Writer, exportName string) error {
	var err error
	if exportName != "init" {
		_, err = fmt.Fprintf(iw,
			"//export %s\n",
			exportName)
		if err != nil {
			return err
		}
	}
	_, err = fmt.Fprintf(iw,
		"func %s() {\n\t// TODO\n}\n\n",
		exportName)
	return err
}
