package main

import (
	"fmt"
	"math"
	"math/rand/v2"
	"os"

	"github.com/mjwhitta/babble"
)

func byteMap(fn string) error {
	var b []byte
	var e error

	for i := range math.MaxUint8 + 1 {
		b = append(b, byte(i))
	}

	rand.Shuffle(
		math.MaxUint8+1,
		func(i int, j int) {
			var tmp byte = b[i]

			b[i] = b[j]
			b[j] = tmp
		},
	)

	//nolint:mnd // u=rw,go=-
	if e = os.WriteFile(fn, b, 0o600); e != nil {
		return e
	}
	return nil
}

func scObfuscator(scFile string) error {
	var e error
	var k *babble.Key
	var enc_bytes []byte
	var dllpayloadfilename string = "dll/payload_generated.go"
	var dllpayloadfile *os.File
	var footer string = "-----END BABBLE-----"
	var header string = "-----BEGIN BABBLE-----"
	var keyFile string = "dll/key_generated.bin"

	e = byteMap(keyFile)
	checkError(e)

	k, e = babble.NewKeyFromFile(keyFile, &babble.ByteMode{})
	checkError(e)

	enc_bytes, e = babble.EncryptFile(scFile, k)
	checkError(e)
	enc_bytes = enc_bytes[len(header) : len(enc_bytes)-len(footer)]

	dllpayloadfile, e = os.Create(dllpayloadfilename)
	checkError(e)
	defer dllpayloadfile.Close()

	dllpayloadfile.WriteString(
		"// Code generated by Johnny Dllaze; DO NOT EDIT.\n",
	)
	dllpayloadfile.WriteString(
		"package main\n\n",
	)
	dllpayloadfile.WriteString("var buf = []byte { ")
	for i := 0; i < len(enc_bytes); i++ {
		tmpstr := fmt.Sprintf("%v", enc_bytes[i])
		if i != (len(enc_bytes) - 1) {
			tmpstr += ", "
		}
		dllpayloadfile.WriteString(tmpstr)
	}
	dllpayloadfile.WriteString(" }\n\n")
	return nil
}
